# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Interface2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1253, 377)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imageProcessor = QtWidgets.QPushButton(self.centralwidget)
        self.imageProcessor.setGeometry(QtCore.QRect(670, 20, 91, 41))
        self.imageProcessor.setObjectName("imageProcessor")
        self.image_explorer = QtWidgets.QLineEdit(self.centralwidget)
        self.image_explorer.setGeometry(QtCore.QRect(30, 20, 521, 41))
        self.image_explorer.setObjectName("image_explorer")
        self.fileFinder = QtWidgets.QPushButton(self.centralwidget)
        self.fileFinder.setGeometry(QtCore.QRect(560, 20, 101, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileFinder.sizePolicy().hasHeightForWidth())
        self.fileFinder.setSizePolicy(sizePolicy)
        self.fileFinder.setMaximumSize(QtCore.QSize(167, 167))
        self.fileFinder.setObjectName("fileFinder")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 80, 331, 241))
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setPixmap(QtGui.QPixmap("check_default.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(550, 70, 471, 271))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.progressBar_9 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_9.setGeometry(QtCore.QRect(10, 40, 381, 23))
        self.progressBar_9.setProperty("value", 0   )
        self.progressBar_9.setObjectName("progressBar_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 381, 23))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 121, 16))
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar.setGeometry(QtCore.QRect(10, 30, 381, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_2.setGeometry(QtCore.QRect(10, 90, 381, 23))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 381, 23))
        self.label_4.setObjectName("label_4")
        self.progressBar_3 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_3.setGeometry(QtCore.QRect(10, 150, 381, 23))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(self.tab_2)
        self.progressBar_4.setGeometry(QtCore.QRect(10, 210, 381, 23))
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName("progressBar_4")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 381, 23))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.imageWindow = QtWidgets.QLabel(self.centralwidget)
        self.imageWindow.setGeometry(QtCore.QRect(40, 80, 331, 241))
        self.imageWindow.setTextFormat(QtCore.Qt.RichText)
        self.imageWindow.setPixmap(QtGui.QPixmap("check_default.png"))
        self.imageWindow.setScaledContents(True)
        self.imageWindow.setObjectName("imageWindow")
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Checker"))
        self.imageProcessor.setText(_translate("MainWindow", "Process"))
        self.fileFinder.setText(_translate("MainWindow", "Open"))
        self.label_10.setText(_translate("MainWindow", "Stego Percentage"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Binary Classification"))
        self.label.setText(_translate("MainWindow", "Cover Image"))
        self.label_2.setText(_translate("MainWindow", "JMiPOD Image"))
        self.label_4.setText(_translate("MainWindow", "JUNIWARD Image"))
        self.label_3.setText(_translate("MainWindow", "UERD Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Classifcation"))

